### ISSUE TITLE
Start jupyter automatically on EC2 boot

### ISSUE THREAD

**Issue by riastradh-probcomp** [probcomp/probcomp-stack#3]
Currently we ssh in and run `nohup jupyter notebook --no-browser --ip=\*` and then log out.  This is silly.  We should arrange it to start automagically.

**Comment by axch** [comment]
An issue: We currently customize the jupyter notebook UI a little by dumping some stuff from workshop-materials/custom to ~/.jupyter/custom on the instance.  Apparently the Jupyter server needs to be restarted for such a change to take effect.

Also, we start the server in a subdirectory named ~/notebook (where the content is to be dumped), so that the users are not distracted by stuff that shows up in $HOME.

**Comment by axch** [comment]
Fixed and manually tested working as of 9bb51d292ef2a92da5f975711d72e46c9f6c6513
